development:
  adapter: postgresql
  encoding: unicode
  database: 3L_development
  pool: 5
  username: xyz
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: 3L_test
  pool: 5
  username: xyz
  password: secret