require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FreeTrialsController do

  # This should return the minimal set of attributes required to create a valid
  # FreeTrial. As you add validations to FreeTrial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FreeTrialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all free_trials as @free_trials" do
      free_trial = FreeTrial.create! valid_attributes
      get :index, {}, valid_session
      assigns(:free_trials).should eq([free_trial])
    end
  end

  describe "GET show" do
    it "assigns the requested free_trial as @free_trial" do
      free_trial = FreeTrial.create! valid_attributes
      get :show, {:id => free_trial.to_param}, valid_session
      assigns(:free_trial).should eq(free_trial)
    end
  end

  describe "GET new" do
    it "assigns a new free_trial as @free_trial" do
      get :new, {}, valid_session
      assigns(:free_trial).should be_a_new(FreeTrial)
    end
  end

  describe "GET edit" do
    it "assigns the requested free_trial as @free_trial" do
      free_trial = FreeTrial.create! valid_attributes
      get :edit, {:id => free_trial.to_param}, valid_session
      assigns(:free_trial).should eq(free_trial)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FreeTrial" do
        expect {
          post :create, {:free_trial => valid_attributes}, valid_session
        }.to change(FreeTrial, :count).by(1)
      end

      it "assigns a newly created free_trial as @free_trial" do
        post :create, {:free_trial => valid_attributes}, valid_session
        assigns(:free_trial).should be_a(FreeTrial)
        assigns(:free_trial).should be_persisted
      end

      it "redirects to the created free_trial" do
        post :create, {:free_trial => valid_attributes}, valid_session
        response.should redirect_to(FreeTrial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved free_trial as @free_trial" do
        # Trigger the behavior that occurs when invalid params are submitted
        FreeTrial.any_instance.stub(:save).and_return(false)
        post :create, {:free_trial => { "email" => "invalid value" }}, valid_session
        assigns(:free_trial).should be_a_new(FreeTrial)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FreeTrial.any_instance.stub(:save).and_return(false)
        post :create, {:free_trial => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested free_trial" do
        free_trial = FreeTrial.create! valid_attributes
        # Assuming there are no other free_trials in the database, this
        # specifies that the FreeTrial created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FreeTrial.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => free_trial.to_param, :free_trial => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested free_trial as @free_trial" do
        free_trial = FreeTrial.create! valid_attributes
        put :update, {:id => free_trial.to_param, :free_trial => valid_attributes}, valid_session
        assigns(:free_trial).should eq(free_trial)
      end

      it "redirects to the free_trial" do
        free_trial = FreeTrial.create! valid_attributes
        put :update, {:id => free_trial.to_param, :free_trial => valid_attributes}, valid_session
        response.should redirect_to(free_trial)
      end
    end

    describe "with invalid params" do
      it "assigns the free_trial as @free_trial" do
        free_trial = FreeTrial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FreeTrial.any_instance.stub(:save).and_return(false)
        put :update, {:id => free_trial.to_param, :free_trial => { "email" => "invalid value" }}, valid_session
        assigns(:free_trial).should eq(free_trial)
      end

      it "re-renders the 'edit' template" do
        free_trial = FreeTrial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FreeTrial.any_instance.stub(:save).and_return(false)
        put :update, {:id => free_trial.to_param, :free_trial => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested free_trial" do
      free_trial = FreeTrial.create! valid_attributes
      expect {
        delete :destroy, {:id => free_trial.to_param}, valid_session
      }.to change(FreeTrial, :count).by(-1)
    end

    it "redirects to the free_trials list" do
      free_trial = FreeTrial.create! valid_attributes
      delete :destroy, {:id => free_trial.to_param}, valid_session
      response.should redirect_to(free_trials_url)
    end
  end

end
